### ISSUE TITLE
Question: does this work across nodes?

### ISSUE THREAD

**Issue by jonathanleang** [whitfin/cachex#119]

**Comment by whitfin** [comment]
Can you please be more specific? You can do basically anything across nodes... if you build your app right :)

**Comment by jonathanleang** [comment]
I am new to Elixir/erlang/OTP started 4 weeks ago coming from node.js, 
my question is when some value is set into cachex will another node(server) be able to get the value, for my use case I don't want the data to copy into multiple node (ie. don't want mnesia's net split, merge issues), but want another node to read and update it. can cachex do this? , maybe I need Elixir's registry and make a gen_server? (as I am new to elixir I only read they are the thing I need but haven't made one yet.)

Here is my use case, is cachex sultable ? 
Imagine a game server there are many items that needs to be updated from multiple nodes, currently everything in in a progressql db, since its is write heavy I want to be able to hold the data in one of the node's process and flush it to db via a timer or when process is killed. Am I looking at cachex wrong and I should just keep the data in the process and do without putting it in a cache or ETS?

**Comment by whitfin** [comment]
Hi @jonathanleang,

It's not really the best use case, but that's more because the design itself isn't ideal. It would be better for each node to have their data in memory and each flush on interval, rather than have them all talking to each other.

You could keep the data in the process, but that's slightly less safe as a crash in the process will mean you lose your data. ETS is a good use case, but Cachex is basically convenience wrapped around ETS (ETS is basically key/value storage) so you would be better off using Cachex for the additional feature set (especially seeing as you're new to the language, since ETS is at the Erlang level).

But, that being said, you can totally fit your use case by just RPC'ing Cachex calls across to your main node, there's nothing stopping that from happening. 

Does that make sense?

**Comment by jonathanleang** [comment]
Hi @whitfin,

yeah that makes sense, thanks ! 

Is the design I described uncommon in erlang/OTP world ? I think I got that idea watching erlang stuff on youtube, or maybe I understanded it wrong ? 

If each node have their own data and flush to database, how do I deal with overwrites and merge issues ?

How can I set cachex so that it will not delete my data until my process is gone, ie no Cache Limits.

**Comment by whitfin** [comment]
@jonathanleang it's not really an Erlang specific design, so not really.

You would have to handle that in your app layer. If you want to only do it from one node, there's nothing stopping you doing that :)

That's the default behaviour, so nothing!

**Comment by jonathanleang** [comment]
Thanks  @whitfin  very helpful.
