### ISSUE TITLE
Migrate fallbacks to live in a new fetch/4 function

### ISSUE THREAD

**Issue by tlvenn** [whitfin/cachex#126]
I have been using con_cache and there is one function that I end up using quite frequently with it which is `get_or_store/3` which has the following semantic:

```
# Returns existing value, or calls function and stores the result.
# If many processes simultaneously invoke this function for the same key, the function will be
# executed only once, with all others reading the value from cache.
```

I think it would be a good addition to the api.
@whitfin what do you think ?

**Comment by tlvenn** [comment]
Nevermind, the fallback option actually accomplish this already...

Since I am not the first one to trip on this, I wonder if it would be worth it to still provide something explicit such as `get_or_store` which would simply delegate to `get` passing the fun as fallback.

What are the guarantee around concurrent executions ? Are they the same as described above ?

**Comment by whitfin** [comment]
Woohoo, I came here to tell you to read the docs but it appears you have now! 👍 

I'm totally against providing `get_or_store` simply because there's no reason to copy it just because another project has it (plus I hate the name, I'd rather use `compute` or something).

However, I have been considering making the `fallback` option more explicit in `get` calls, in that you can either do:

```elixir
Cachex.get(name, key, [ fallback: ... ])
```

or (new behaviour):

```elixir
Cachex.get(name, key, fn(_key) -> 
   ...
end)
```

This would change the function signature in the documentation, perhaps making it a little more obvious that you can use it to compute a value. Internally, of course, the latter would just call the former (so it's literally just sugar). 

What do you think about this? Does this sound like a good compromise?

**Comment by tlvenn** [comment]
Yep that would be perfect, promoting the fallback as an explicit third argument will do the trick very nicely.

**Comment by tlvenn** [comment]
Btw can you comment on exactly what is the behaviour of Cachex in case of concurrent execution with the fallback ? Is there any guarantee that the fallback will be called only once ?

**Comment by whitfin** [comment]
@tlvenn ok, will tweak the issue title and schedule for v3.

Right now fallbacks will just all fire at once and first one wins (because unlike con_cache, caches aren't running inside a GenServer). 

See #96, which will provide the guarantee you're wanting.

**Comment by whitfin** [comment]
Hey again @tlvenn!

I took a shot at this yesterday but I don't like having arguments which have multiple types (e.g. function or list), so I'm now against putting it in the `get` signature.

I'm thinking of adding a new function in its place, what do you think of the name `compute`? I might actually move fallbacks totally out of `get` and make fallbacks go through `compute` all the time, unless you object?

Since the next release is v3 and breaks stuff anyway, this is a viable option.

**Comment by tlvenn** [comment]
That's great, thanks !
