### ISSUE TITLE
Can Cachex be used on more than one node?

### ISSUE THREAD

**Issue by vfsoraki** [whitfin/cachex#149]
I am scaling my application from 1 node to 2. I use Cachex in my application.

I don't want the two nodes to have different caches, so is there a way to start Cachex application on two nodes and connect them toghether somehow? Or I should do it with my own middleware?

**Comment by whitfin** [comment]
Hi @vfsoraki!

Yes, but it's not part of the library itself (because everyone needs slightly different behaviour). You can use `:rpc` to call over to a "master" node that holds the cache, for example. Distribution is hard enough that it shouldn't be solved inside Cachex, rather it should be solved separately and integrated.

A simple solution is just to use Redis as your distributed cache, and then have your application nodes use Cachex with a TTL and just cache the Redis results locally. That would give you easy distribution. 

If you want to avoid Redis as a dependency, you could do the same pattern with a new Cachex node which you RPC to and make changes that way. Really it's up to you.

I'm going to close this as it's not a library issue, but I'm perfectly happy to have discussion on here!

**Comment by vfsoraki** [comment]
Aa my first try, I tried to make cache global, using `{:global, :my_cache}` as name when starting cache as worker under supervisor.

It fails with error `:invalid_name`, so it is not possible. I think this can be something to work on.
