### ISSUE TITLE
Don't suppress errors on proactive warming

### ISSUE THREAD

**Issue by quolpr** [whitfin/cachex#176]
We will never know if proactive warmer failed because of this https://github.com/whitfin/cachex/blob/master/lib/cachex/warmer.ex#L94 . Can we add callback or `Logger.error` support?

**Comment by whitfin** [comment]
@quolpr I actually considered this when writing warmers!

In the end I decided that if you really have something which can fail, you should explicitly be handling it in the warmer itself (and thus logging, or whatever you want to do). The `try/rescue` in the warmer code itself is purely a last resort to stop bad runs of a warmer crashing the tree. 

I would suggest just handling your errors inside the warmer itself. Let me know if this makes sense!

**Comment by quolpr** [comment]
The real problem is that I spent too much time on understanding why cache was not working. The output console was empty and I thought that my code is working fine and problem in connected with cachex(actually problem was connected with my code).

I think it still not good default behaviour. I still think, that developer should get known, that his code failed

**Comment by quolpr** [comment]
Why we can't allow just fall the code?

**Comment by whitfin** [comment]
@quolpr I understand but if you have code that can cause a crash, surely you should already be aware of that, no? You said yourself that the issue was in your code rather than Cachex; it should be up to your unit tests to catch those issues (in general).

The problem with just restarting is that you lose the state you had when it crashed - and warmers can inherently crash due to events such as connection issues with a database, etc. In those cases you want your state preserved, not lost. I agree that a developer should be explicit about this, but at the same time if I change this I imagine that sometime in the future someone will file an issue to catch all errors :)

I'll consider it; if I take out the rescue and everything still passes in the unit tests then I'll be more likely to change this going forward.

**Comment by whitfin** [comment]
@quolpr this has been changed in https://github.com/whitfin/cachex/commit/b1459343773167045b0e027f033919aa18eb5e2e. Shouldn't cause issues for existing users, so no point waiting.

**Comment by quolpr** [comment]
@whitfin btw, are you sure that it is a good idea to break default behavior? Maybe it will be better just to add config option to not suppress errors

**Comment by whitfin** [comment]
@quolpr given that this is a better pattern for OTP, and that people typically handle their errors anyway, I'm comfortable with changing this.
