### ISSUE TITLE
ttl option for fetch?

### ISSUE THREAD

**Issue by sickill** [whitfin/cachex#177]
I've just noticed that while `put` supports specifying ttl, `fetch` doesn't. There's `options` argument to `fetch` but passing `ttl: 5000` doesn't set ttl on the key when fallback fn is used.

Given that `fetch` is a combination of `get` + `put`, it makes sense to me to allow passing ttl there too. 

What do you think? If you're interested I could propose a PR.

Thanks!

**Comment by sickill** [comment]
Meanwhile I've built my own `fetch` alternative with `transaction`:

```elixir
  def fetch(name, key, ttl, f) do
    Cachex.transaction!(name, [key], fn cache ->
      with {:ok, nil} <- Cachex.get(cache, key) do
        value = f.()
        Cachex.put!(cache, key, value, ttl: ttl)
        {:ok, value}
      end
    end)
  end
```

**Comment by whitfin** [comment]
Hi @sickill!

The `:ttl` flag cannot be supported with `fetch/4` due to some internals and optimizations. If you call `fetch/4` from two places at the same time, with different `:ttl` options, there's no way to know which takes effect.

The pattern you have is functional, but this would be much better for both throughput and correctness:

```elixir
with { :commit, result } = Cachex.fetch(cache, key, f) do
  Cachex.expire(cache, key, ttl)
  { :commit, result } 
end
```

Let me know if this makes sense!

**Comment by sickill** [comment]
@whitfin wouldn't this bump the ttl every time I call it?

**Comment by whitfin** [comment]
@sickill no; because you only get `{ :commit, _ }` when the value was written. If the value already existed, you'd get an `{ :ok, _ }` result instead :)

**Comment by sickill** [comment]
Ah, of course. That sounds like a simple solution. Then probably adding ttl to `fetch` is not worth it. Thanks!
