### ISSUE TITLE
New process is spawned whenever fetch/4 fallback is called.

### ISSUE THREAD

**Issue by jung-hunsoo** [whitfin/cachex#185]
I recently found that when the fallback function in `fetch/4`  has called, it has a new process id.

Though I haven't read through the codes, it seems that it actually doesn't need to spawn a new process. This may be a point for performance improvement.

Any other thoughts?

**Comment by whitfin** [comment]
Hi @jung-hunsoo!

You are correct that fallback blocks run in another process, however there's a single process rather than one per fallback. This is desired as it acts like a queue, which stops multiple code locations all loading at the same time.

Consider the case of 1,000 cache calls per second, and say your cache has a fallback to a database, which takes 5 seconds to load. If there was no backing queue, you would end up with 5,000 calls to your database before the cache is correctly populated. The way things are structured now, there is a single call, and all 5,000 cache calls will return at the same time.

I'm going to close this, as it's entirely desired and intentional, but feel free to ask more questions!
