### ISSUE TITLE
Does using dynamic number of nodes require restarting Cachex?

### ISSUE THREAD

**Issue by syamilmj** [whitfin/cachex#199]
Since the `:nodes` options is provided at runtime, it seems that there isn't a way for the application to update the list of nodes other than restarting Cachex.

Is this correct?

**Comment by syamilmj** [comment]
Thanks for the clarification.

I have been using Cachex as distributed cache, by writing a simple wrapper on top of it instead of using the `:nodes` option (it didn’t exist yet back then).

Would love to take a stab at a PR to expand on this feature, if you’re open for that?

The idea I have in mind is to add some sort of Adapter pattern, as such:

```
Supervisor.start_link(
  [worker(Cachex, [:my_cache, [
    persistent: true,
    distributed: true,
    adapter: Cachex.Adapter.Mnesia
  ]]) ]
)
```

The idea is user doesn’t need to worry about defining any nodes when starting the app, and instead let the adapter handles nodes discovery & reconnection.

**Comment by whitfin** [comment]
I'm against anything like that model because I do not want to have Cachex be responsible for discovery/reconnection/any of that. If I were to add this to Cachex, it would simply be in the form of `add_nodes/2` and `remove_nodes/2` pretty much. You could call those when you've discovered new nodes yourself, to update the Cachex listing.

**Comment by syamilmj** [comment]
Fair enough. Is this something you already have in the pipeline? I’d be happy to contribute.

**Comment by whitfin** [comment]
@syamilmj before we even look at code, we need to think through exactly how feasible it is.

If a node is removed from a cluster, what should the behaviour be with regards to balancing? How can we be sure that keys are still directed to the same nodes as previously? Adding nodes is fairly simple, but removing is more complicated.

**Comment by syamilmj** [comment]
@whitfin does current implementation balances the keys between nodes?

I think we can do away with eventual consistency, treating cache as temporal data store, not storage. What this means basically as soon as a node gets disconnected, it will have to rebuild its cache.

**Comment by whitfin** [comment]
@syamilmj yes, keys are sharded across the cluster. 

This is definitely not an option. Any changes must enhance what is currently offered; we can't just remove stuff to make add/remove nodes work :)

**Comment by relistan** [comment]
@whitfin you just use a consistent hash instead. Then only a portion of the keys need to be redistributed. https://en.m.wikipedia.org/wiki/Consistent_hashing

**Comment by whitfin** [comment]
@relistan Cachex does actually already use a consistent hash as I planned on adding/removing nodes in future.

The issue is rebalancing. If a node drops out, I don’t want to be writing balancing logic in what is essentially a small caching library. If you have nodes A, B, and C, and drop out B, everything from B could go to C but everything that was on C would no longer route properly.

That’s the problem we need to solve elegantly, in general terms. Addition of nodes is fairly straightforward (kinda... it gets hard).

**Comment by relistan** [comment]
@whitfin sorry, I missed the dependency on Jumper in my first pass. It may be that Google's jump hash is not well suited to this application and that this is the problem. From the abstract from the Google paper:

> Its main limitation is that the buckets must be numbered sequentially, which makes it
more suitable for data storage applications than for distributed web caching.

Since you are using it for web caching, it's probably not the right fit. Further down in the paper, they describe how jump is different from other consistent hashes (emphasis mine):

>Both of these algorithms allow buckets to have arbitrary ids, and handle not only new buckets
being added, **but also arbitrary buckets being removed. This ability to add or remove buckets in
any order can be valuable for cache servers where the servers are purely a performance
improvement.** But for data storage applications, where each bucket represents a different shard
of the data, it is not acceptable for shards to simply disappear, because that shard is only place
where the corresponding data is stored.

Essentially jump is built for data sharding where you can't ever lose a shard. For _caching_ where you are working with ephemeral data and actively desire the ability to grow and shrink the pool, it seems it's not a very good fit.
