### ISSUE TITLE
Async tests with cachex

### ISSUE THREAD

**Issue by popo63301** [whitfin/cachex#213]
Hi! 

I'm wondering how would I handle async tests with Cachex. I don't want to have race conditions with my test suites so I'd like to know if Cachex handles async tests already or do I have to do something else? 

Thanks !

**Comment by whitfin** [comment]
Yes, it’s fine to use async tests. The only race conditions would be those involving your code interacting with Cachex.

**Comment by popo63301** [comment]
Actually, I just made a test and my code was interacting with Cachex. I wanted to isolate all transactions I made to Cachex the same way Ecto's Sandbox mode works. That would be a great feature to implement. :D

**Comment by whitfin** [comment]
You can simply call ‘Cachex.reset’ in a ‘setup’ block.

**Comment by popo63301** [comment]
Well, that's not enough if tests are run in parallel. I find this feature really interesting. I'll try to find some time to work on it 😄

**Comment by whitfin** [comment]
If you want to sandbox, either use a new cache when async, or reset and run sync.

There’s no need to change anything in Cachex for this. If your code has races in how you deal with a cache, then it definitely _should_ fail tests. Sandboxing would only cause false confidence.

**Comment by popo63301** [comment]
I thought about running a new cache on setup but that implies that my code implied with cachex should know where to get directed for each test. For example, if I have a function that interacts with :album table and I run 3 tests in parallel interacting with the same table name, there is a need for a mechanism that will connect :album to, say, :album1/:album2/:album3 . It's not that obvious to build (at least, I don't know at the moment how to do that) and  it's either this or building a sandbox mode.

"There’s no need to change anything in Cachex for this.": Redirecting to a specific cache or using a sandbox requires some changes in the code. Except if you have a better solution. 😄  

"If your code has races in how you deal with a cache, then it definitely _should_ fail tests.": Humm... yeah. That's obvious. That's why races conditions are a problem. 

"Sandboxing would only cause false confidence." : Sandboxing (at least, the definition I know from what Ecto provides) provides a mechanism to run tests in parallel. Tests are made to build confidence. A sandbox mode will help run tests faster, so it will help build confidence faster. Thus, I don't understand why sandboxing would cause false confidence.

**Comment by whitfin** [comment]
There is a little confusion (probably from other languages) in your approach. The only way there's a supposed race condition if you run 3 tests at the same time on the same cache is when they use the same cache keys. For example, TestA inserts Key1 and TestB removes it before TestA has a chance to use it for anything.

But this is not a problem with Cachex in tests. It's either the fault of the developer for writing (what is essentially) a flakey test, or it's the fault of the developer for not using transactions in their caching code when they're needed. 

The fact that several tests can use a cache at the same time is not the point. The point is, in your production code, will you use a cache from several processes at the same time? If the answer is yes, then sandboxing your tests is false confidence because they're not testing the flow you're shipping to production. It doesn't matter if your tests are "async safe" if your actual code is not. If the answer is no, then perhaps restrict access to your cache behind a GenServer to enforce this behaviour.

The use of a "sandbox" is far too focused on the state of your test code, which is not where your priority should be. Your proirity is the state of your production code; if your tests fail randomly because you're using your production code from 3 places at once, then it should be the production code that is strengthened, not the test code.

Does this make sense? In essence, you're asking the wrong question; it's whether your code supports async tests or not, rather than Cachex.

**Comment by popo63301** [comment]
Maybe I should be more clear by explaining my goal first. My goal is to build apps that will use caching for different reasons (e.g.: fetching users id quickly, avoid round-trips to databases, and so on). Also, I want to be confident when shipping my code so I will build some integrations tests with Hound and I want to run my test suites faster with async mode. 

I will probably use the same fixtures in different tests so I don't want to bother myself changing the names of my data sets just so that I'm sure I won't have the same keys in my cache running my tests in parallel. I want to use a cache to avoid going to the database, so it's almost like a database. That's exactly the point of sandboxing. 

"The fact that several tests can use a cache at the same time is not the point. The point is, in your production code, will you use a cache from several processes at the same time?" : I know that you've been working on multi-process cache feature and I want to thank you for your work. I believe ensuring that the cache will work in several processes relies on the tests of the library itself. When I'm testing my code, this is not my point. My point is simply to run my test suites faster by doing it asynchronously. 

By the way, I'm sure there are a lot of people out there who might need to run tests asynchronously using a cache and surely, they would want to be confident using the same keys name won't trigger race conditions so that's perfect.

**Comment by whitfin** [comment]
Ok, seeing as this is going around in circles: you absolutely can run tests against a cache asynchronously. Nothing in the Cachex codebase is written in a way that it's going to break when called from multiple processes; it's designed with this in mind.

If you have further questions, let me know.
