### ISSUE TITLE
Cachex.Warmer Dialyzer Issues

### ISSUE THREAD

**Issue by asummers** [whitfin/cachex#230]
Because the `Cachex.Warmer` macro explicitly matches on all possible returns from `execute`, consumers that do not return (e.g.) `:ignore` from their warming functions get Dialyzer errors saying that they will never execute this pathway. If the macro instead called out to functions (e.g. `Cachex.Warmer.init`, `Cachex.Warmer. handle_info`, and similar), Dialyzer would not be able to confidently say that path was not exercised. This has an additional benefit whereby if someone needed to get the default `handle_info` behavior with some modifications, there is not a function they can invoke without copying the `__using__` macro contents into their own code directly.

**Comment by whitfin** [comment]
This is definitely not an issue, as the use case you described is ignoring the contract of the public API described in the documentation. There should be no consumers that do not return `:ignore`, because that's wrong in the eyes of the public API. In this regard, it is correct that Dialyzer is warning you.

It is very unlikely this will change, because Dialyzer is only enforcing what is already documented as the correct behaviour. I don't see a benefit in somehow making this warning unraised, rather it feels like a negative change.
