### ISSUE TITLE
Breaking changes in 3.20

### ISSUE THREAD

**Issue by axelson** [whitfin/cachex#233]
I'm trying to upgrade from cachex 3.1.3 to 3.2.0 and some tests are failing

Errors mostly look like:

`** (Protocol.UndefinedError) protocol Enumerable not implemented for {:ok, [{"776f3ab8-8395-4ddd-9645-a367de9e7231", nil}, {"17e4819a-4a2c-40a3-8c09-e7aece7932d4", nil}]}. This protocol is implemented for: Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, StreamData, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream`

Are there any expected breaking changes in 3.2.0? (I couldn't find any listed in docs or issues)

**Comment by whitfin** [comment]
@axelson without seeing your code, I can't say for sure what issue you hit.

However, I believe some return types were corrected in 3.2.0 (which were technically just broken prior to that). This appears to be one of them, where you might wish to use `stream!` instead of `stream` to achieve the previous behaviour.
