### ISSUE TITLE
Feature Request: Cache Warmer that doesn't block startup

### ISSUE THREAD

**Issue by axelson** [whitfin/cachex#280]
I'm using a Cachex.Warmer in a code path that is tangential to the application that I'm working on. So I don't want to take a hit on startup time by waiting for the cache to be ready. If I serve a couple requests in the meantime I am not worried. I see that this was originally possible in the initial version of https://github.com/whitfin/cachex/pull/244 but it was later removed.

**Comment by whitfin** [comment]
Hi @axelson!

Way too late to this but the points in the link you provided still stand; in terms of correctness the behaviour we have now is far better than non-blocking.

That being said, I am willing to consider an option to toggle it off (I think I put that in the linked comments too). I'll think about it a little more (since I'm doing some cleanup stuff in the repo anyway), and include it any release should I decide to add it.

**Comment by axelson** [comment]
Thanks for the consideration! Making the blocking/non-blocking behavior configurable would be great in my opinion.

**Comment by whitfin** [comment]
This will be tracked and merged for v3.5.0 in https://github.com/whitfin/cachex/pull/294 - just still deciding on names for flags.

**Comment by axelson** [comment]
Great, thanks! I'm excited to try it out 🎉
