### ISSUE TITLE
Set TTL in fallback read-through cache

### ISSUE THREAD

**Issue by BrendanBall** [whitfin/cachex#288]
I'm trying to implement a read-through cache with the fallback option, but it doesn't seem to support setting a TTL with `:commit`.

I could do the following:
```elixir
{value, ttl} = Cachex.fetch(:my_cache, "key", fn(key) ->
  { :commit, {String.reverse(key), ttl} }
end)
Cache.expire(:my_cache, "key", ttl)
```
But this means I have to store the ttl with the value.
This is also a problem for the courier, since the fallback is executed only once for all pending fetches, but the `Cache.expire(:my_cache, "key", ttl)` will be executed for all pending fetches.

> As of v3, fallbacks changed quite significantly to provide the guarantee that only a single fallback will fire for a given key, even if more processes ask for the same key before the fallback is complete

Am I missing something or are fallbacks/read-through caches currently missing some features?

**Comment by whitfin** [comment]
You are correct that this is not available. There are many reasons for this, but specifically in your case you state:

> But this means I have to store the ttl with the value.

This implies that you are generating a TTL inside the fallback function itself, which is a fairly odd pattern. Most usage would have a TTL defined before executing a fallback, which lends itself to this pattern:

```elixir
with { :commit, _val } <- Cachex.fetch(:my_cache, cache_key, &my_func/1) do
  Cachex.expire(:my_cache, cache_key, :timer.seconds(1))
end
```

This also already covers your case of the `expire/3` call happening regardless of result of the `fetch/3` call.

**Comment by BrendanBall** [comment]
Well it's a fairly valid use case for example different http resources with different TTL's or in my case different DNS records with different TTL's.

But doesn't this pattern still result in `expire/3` being called multiple times?:
```elixir
with { :commit, _val } <- Cachex.fetch(:my_cache, cache_key, &my_func/1) do
  Cachex.expire(:my_cache, cache_key, :timer.seconds(1))
end
```
For example if 10 different processes run this simultanously then the fallback would only run once because of the courier, but the `expire/3` would be run 10 times? So this is still a problem even if the TTL doesn't come from the fallback?

**Comment by whitfin** [comment]
> Well it's a fairly valid use case for example different http resources with different TTL's or in my case different DNS records with different TTL's.

Yeah, I wasn't saying it was invalid, just that it wouldn't be common - which is why it hasn't been included yet. Most usage I've see that have asked for this could accomplish it with the pattern above. 

The main issue I've had with adding support for your use case in the past is that there isn't really any nice way to support it from within the fallback, beyond something like `{ :commit, val, ttl }` or maybe `{ :commit, val, options }`.

As stated in [here](https://github.com/whitfin/cachex/blob/master/docs/features/ttl-implementation.md#key-expirations), Cachex is already moving away from `:ttl` as an option in favour of explicit expire calls. People have asked for `:ttl` to be supported in the options provided to `fetch/4`, as well as now (in your case) being provided from inside the fallback itself; it just leads to a lot of places to have to handle the option. Having everything done through expire calls is a lot simpler. 

> For example if 10 different processes run this simultanously then the fallback would only run once because of the courier, but the expire/3 would be run 10 times? So this is still a problem even if the TTL doesn't come from the fallback?

You're right as it stands, but I'm trying to decide if I think this is a bug or not. I think realistically, the first call that triggered the courier should be the only one that returns `{ :commit, val }`, and any that are waiting on that should return `{ :ok, val }` after resolution. At least if this is corrected, you can use the pattern provided above with the slight caveat of putting your TTL in the cache entry - as you already mentioned. Thoughts on this?

**Comment by whitfin** [comment]
Just dropping a note to say that https://github.com/whitfin/cachex/pull/295 will resolve the behaviour you pointed out with multiple fetch calls happening at the same time.

**Comment by BrendanBall** [comment]
awesome thanks :smile:
