### ISSUE TITLE
Potential memory issues with LRW policy

### ISSUE THREAD

**Issue by johantell** [whitfin/cachex#300]
Hello, I just wanted to chip in and ask some questions around the LRW policy and it's usage since I've experienced problems when activating the policy (rather than not having a policy at all).

What happened was that after activating the policy with this setup:

```elixir
      Supervisor.child_spec(
        {Cachex, [name: :my_cache, limit: Cachex.Spec.limit(size: 750, policy: Cachex.Policy.LRW)]},
        id: :my_cache
      )
```

The server went crazy and allocated enough memory to actually bring it down. I got curious, looked a bit deeper and realized that even though my cache only has allocated around 10Mb of memory

```elixir
iex(1)> Cachex.inspect(:my_cache, {:memory, :binary})
{:ok, "10.57 MiB"}
```
![image](https://user-images.githubusercontent.com/1777129/197993934-e17b5072-4e63-4967-bc90-70e0edb33b5d.png)

I'm seeing the `LRW` and courier processes allocating a ton of memory:

![image](https://user-images.githubusercontent.com/1777129/197993820-97115c52-a381-40db-ae25-7b2a66eeecfb.png)

Which all seems to increase when along with added objects to the cache.

Is it likely that this is due to an invalid configuration or could it potentially be a bug in cachex as the documentation for `LRW` states that it should be extremely lightweight?

**Comment by whitfin** [comment]
Hi @johantell!

I don't think this is a bug, moreso just the nature of the VM (I could be wrong though).

The way LRW works is that when you execute a cache action which can increase the key space, it will check the total size, and trim if required. There's basically nothing actually stored here in terms of state (it's just all ETS). 

That being said, the notification of cache actions being executed is passed to the LRW handler (which is a GenServer), so I imagine that the memory use you're seeing is just the mailbox, which is slow to clean up for some reason.

I'm quite surprised to see the mailbox being that large, but it will definitely scale somewhat to the throughput of your cache (which is why it might seem like it scales to the number actually in the cache). 

I hope this makes sense; if you can think of a better way to approach this I'm happy to look into them. I do have an idea for a more lightweight policy which is time based rather than event based, which would be extremely minimal but also have potential to be outdated (hence the tradeoff).

Sorry for the slow reply, let me know your thoughts!

**Comment by johantell** [comment]
It totally might be and I haven't done the research to actually point at a suspected area of trouble but got scared when I saw how one record of 10mb caused the LRW process to allocate 60MB (I tried it locally so that no other records/actions could interfer).

It would make total sense that the LRW process would keep a data structure with a key-reference and a timestamp to be able to perform its job so I suspected that it might have been something causing it to store the whole object instead of just the key reference. 

So I'm basically shooting in the dark and just wanted to let you know what I experienced in case there was an issue (that wasn't my own 😅). 

If I get the time to look into it I will happily dig deeper but at the moment it seems like I can't motivate it over other business needs as I really like the feature-set and mindset of this library :)

Feel free to close this ticket if you feel like there is no further action.

PS. appreciate the thought of an alternative eviction strategy :heart:

**Comment by whitfin** [comment]
Hi @johantell!

I just wanted to follow up with some changes I made in v3.5.0:

Rather than continue as it was before, I have reworked the default behaviour of `Cachex.Policy.LRW` to operate in a timed loop, rather than as a hook. I do not think that the "instant" checking is something most people will care about, and given that it actually slows cache throughput I feel it was a mistake to do it this way initially.

Given that the internals of the LRW policy were not part of the public API, I decided to make this change to the defaults in a minor version (v3.5.0). In the case someone does need the old behaviour, I have placed it behind a new policy option `:immediate`. I don't particularly like this option name, but it'll do 😅.

The `:immedate` flag accepts a boolean, which defaults to `false`. If `false`, the new behaviour will be used to enforce the LRW policy. A once per second check will be carried out on the cache size, and records will be pruned (in the same way as previously). The frequency is configurable via the `:frequency` flag in the limit options. If the `:immediate` flag is set to `true`, then it will operate as before - listening to cache writes and guaranteeing that it never crosses the limit provided.

I might get around to looking at a better implementation of the immediate implementation, but I think this'll do for the time being. At the very least it'll be a lot more intuitive as to how it works for people!
