### ISSUE TITLE
Transactions not permitting parallel execution

### ISSUE THREAD

**Issue by andrecloutier-pd** [whitfin/cachex#302]
Hey Folks, 

I'm trying to understand whether the following behavior is expected when using `Cachex.transaction`. From my understanding of the documentation, I expected `transaction` to allow for parallel executions to occur on the same instance of a cache and for different keys (aka. row locks vs table locks). Though, what I'm observing is that we're locking on the entire cache. 

To illustrate this, consider the following sample code (using Cachex 3.4.0):
```
  def start_cache do
    Cachex.start_link(:my_cache, [ transactions: true ])
  end

  def spawn_child do
    Enum.each(1..3, fn _ ->
      spawn(fn ->
        key = for _ <- 1..10, into: "", do: <<Enum.random('0123456789abcdef')>>
        log(key, "Acquiring Transaction")
        Cachex.transaction(:my_cache, [key],
          fn _cache ->
            log(key, "In Transaction; Sleeping")
            Process.sleep(5000)
            log(key, "In Transaction; Returning")
            "hi"
          end)
        log(key, "Out of Transaction")
      end)
    end)
  end

  def log(key, msg) do
    IO.puts("#{NaiveDateTime.to_string(NaiveDateTime.utc_now())} pid=#{inspect self()} key=#{key} #{msg}")
  end
```

I get the following output:
```
2022-11-22 23:26:57.805389 pid=#PID<0.1068.0> key=fbdca2a623 Acquiring Transaction
2022-11-22 23:26:57.805393 pid=#PID<0.1069.0> key=46db1afc39 Acquiring Transaction
2022-11-22 23:26:57.805394 pid=#PID<0.1070.0> key=733595c2d7 Acquiring Transaction
2022-11-22 23:26:57.812238 pid=#PID<0.1064.0> key=fbdca2a623 In Transaction; Sleeping

2022-11-22 23:27:02.813192 pid=#PID<0.1064.0> key=fbdca2a623 In Transaction; Returning
2022-11-22 23:27:02.813324 pid=#PID<0.1064.0> key=46db1afc39 In Transaction; Sleeping
2022-11-22 23:27:02.813362 pid=#PID<0.1068.0> key=fbdca2a623 Out of Transaction

2022-11-22 23:27:07.814090 pid=#PID<0.1064.0> key=46db1afc39 In Transaction; Returning
2022-11-22 23:27:07.814221 pid=#PID<0.1064.0> key=733595c2d7 In Transaction; Sleeping
2022-11-22 23:27:07.814252 pid=#PID<0.1069.0> key=46db1afc39 Out of Transaction

2022-11-22 23:27:12.815113 pid=#PID<0.1064.0> key=733595c2d7 In Transaction; Returning
2022-11-22 23:27:12.815260 pid=#PID<0.1070.0> key=733595c2d7 Out of Transaction
```

It appears that despite the unique keys, they end up blocking on each other. Additionally, the provided function is always executed by the same pid. Is this expected?

**Comment by whitfin** [comment]
Hi @andrecloutier-pd!

It's a little confusing, but the short story is that transactions are sequential and handled by a different server, which is why you see the waiting and the same PID. Transactions run one by one in the current implementation of Cachex, to guarantee insertion order of keys, etc.

The documentation and/or comments you may have seen about not locking the entire cache refer to commands running on a cache which are *not* transactions. In your example, everything is one at a time, because you have them all in transactions. However if there were other commands running on other keys (typical `put`, `incr`, etc), they would not be blocked. 

To give you an example, let's say you have a single transaction locking the key `key1` and sleeping for an hour. If you queue a second transaction, that will wait for an hour because it has to ensure that the previous transaction completed before it runs. If you call `Cachex.incr(cache, key2)` from outside of a transaction in this time this will proceed as normal even with the hour wait for transactions, because it's not working on a locked key. If you were to call `Cachex.incr(cache, key1)`, it would then become blocked for an hour as it relies on the locked transaction key.

Does this make sense? I hope I explained it well.

**Comment by andrecloutier-pd** [comment]
Hey @whitfin, thanks for the super fast reply! Yep, that totally make sense. A `transaction` here implies consistency and that's done with serial processing. I should have picked up on this with the hint at the bottom of the [transaction block docs](https://hexdocs.pm/cachex/action-blocks.html#transaction-blocks). ;) 

Thanks again! I'll close this issue out.
