### ISSUE TITLE
Using `ordered_set` type tables to back cache

### ISSUE THREAD

**Issue by camilleryr** [whitfin/cachex#328]
Currently it does not seem possible to pass in an option to dictate the `type` of ets table created.  

I have a use case where an `ordered_set` would provide the optimal path to pull from a cache (where entries are keyed and retrieved based on time interval) and was wondering if you had any thoughts on the viability of extending cachex to allow for that.  Since `set` is the default table type, `ordered_set` should not change the behavior of the cachex in any substantial and any subtle changes in behavior (for `set` tables, keys are equal if they match, for `ordered_set` they match if they compare equal) would be opt in.

Based on my understanding of `ordered_set` tables and my limited understanding of cachex, it seems this *should* be a transparent change that offers more flexibility without the sacrifice of any functionality.  If you think this would be a good addition to the library, I would be happy to create a PR

**Comment by whitfin** [comment]
The reason this was never included was because I didn't want to tie to ETS, but I think at this point that's just guaranteed - so I'm definitely happy to add this. If you want to MR it go ahead! If not I can add it in the next few days hopefully; trying to carve out some time to work on the next release here.
